mozilla/Addon-Tests

pages/mobile/base.py, pages/mobile/home.py, tests/mobile/test_home.py
This is for https://github.com/mozilla/Addon-Tests/issues/738
=> Fix mobile test_sort_by_region failure

tests/desktop/test_homepage.py
Issue https://github.com/mozilla/Addon-Tests/issues/739
=> Adding coverage for other applications menu

conftest.py, pages/desktop/discovery.py, pages/page.py
For issue #745: Sorry @justinpotts, I snagged this away from you.
@stephendonner / @justinpotts r?
=> update the DiscoveryPane class to be aware of --apibaseurl

requirements.txt, tests/desktop/test_reviews.py
=> update datetime to use pytz

tests/desktop/test_statistics.py
Update test to run against dev and stage. Will check for a `200 OK` but continue to skip checks that require timely data.
=> remove skip + do partial test of dev/stage

pages/desktop/regions/search_filter.py, pages/desktop/search.py, tests/desktop/test_search.py
Per issue #755, updating the test to relax the filters to allow more results..
=> Update Complete Themes test

requirements.txt
Tested locally against dev on Mac OS X 10.10.2
=> Upgrade pytest dependencies

.travis.yml, setup.cfg
This tweak fixes Github issue #766.
Nothing exciting, but hopefully I've followed Bob's (excellent) instructions correctly :)
Adding @bobsilverberg for review.
=> Add a setup.cfg file for flake8 (#766)

tests/desktop/test_details_page.py
(This passed against AMO dev: https://pastebin.mozilla.org/8834760.)
=> Fix "...one authors" -> "...one author" typo

pages/desktop/details.py
Fix for #774.
Test failed beause the locator found 'Show the developer's reply to this review' link.
=> fix reviews link locator

pages/desktop/complete_themes.py, tests/desktop/test_installs.py
This fixes issue #773 
Adhoc running at http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/amo.adhoc/11/
@m8ttyB | @rbillings r?
=> Fix test_could_install_theme to address the fact that there may be hidden install buttons present

pages/desktop/regions/island.py, pages/desktop/themes.py, requirements.txt, tests/desktop/test_api_only.py, tests/desktop/test_collections.py, tests/desktop/test_complete_themes.py, tests/desktop/test_details_page.py, tests/desktop/test_details_page_against_xml.py, tests/desktop/test_discovery_page.py, tests/desktop/test_extensions.py, tests/desktop/test_homepage.py, tests/desktop/test_installs.py, tests/desktop/test_layout.py, tests/desktop/test_paypal.py, tests/desktop/test_reviews.py, tests/desktop/test_search.py, tests/desktop/test_statistics.py, tests/desktop/test_themes.py, tests/desktop/test_users_account.py, tests/mobile/test_details.py, tests/mobile/test_extensions.py, tests/mobile/test_home.py, tests/mobile/test_search.py
Replaces previous pull requests #777 and #779.
* Adhoc desktop: http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/amo.adhoc/34/
* Adhoc mobile: http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/amo.mobile.adhoc/8/
Pinging @bobsilverberg or @m8ttyB for review.
=> Switch to native asserts. Fixes #776

LICENSE, README.md
Also add a LICENSE file
This commit should include all of the changes documented in the etherpad [1] in the section for "9/15/15 10:00am to 12:00pm Project READMEs". Specifically, I attempted to address everything under the bullet point entitled "Changes decided - using https://github.com/mozilla/Addon-Tests/blob/master/README.md as an example".
As this was a team effort, and we are hoping to use this as a template for all of our other repos, I would appreciate a review from all team members. That includes @davehunt, @m8ttyB, @rbillings, @krupa and @stephendonner.
Thanks everyone!
=> Update the README file to reflect the decisions made during the team meetup

pages/desktop/regions/sorter.py
This fixes #787
Adhoc running at http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/amo.adhoc/35/
@davehunt r?
=> Change locator for updating dialog that appears when sorting

pages/desktop/addons_site.py
=> Fix locator following mozilla/olympia#720

README.md, requirements.txt
Adhoc jobs:
http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/amo.adhoc/46/
http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/amo.mobile.adhoc/11/
Pinging @mozilla/web-qa-sorcerers for review.
=> Update requirements and add badge to README

pages/desktop/details.py, pages/desktop/search.py
It appears my issues were related to running a trunk version of the Selenium server. Whilst this may mean the next release has some exciting issues in store, it's not needed for the current releases.
=> Revert scrolling

pages/desktop/paypal_popup.py
This addresses an intermittent failure as seen at https://webqa-ci.mozilla.com/view/Buildmaster/job/amo.dev.saucelabs/748/
@mozilla/web-qa-sorcerers r?
=> Add a wait for PayPal login to complete

conftest.py, requirements.txt
There's a breaking change in v1.2.0, so I've released a candidate so that we can update our suites before the general release. @rbillings r?
=> Update to pytest-selenium 1.2.0

tests/desktop/test_reviews.py
xfailing the test to add a new review  until https://github.com/mozilla/Addon-Tests/issues/821 is fixed.
=> xfailing the test to add a new review

requirements.txt
Tested locally, all seems well:
`Successfully installed cryptography-1.3.1 idna-2.1 pytest-2.9.1 pytest-variables-1.4 pytz-2016.3 setuptools-20.3.1
(addon-tests) sdonners-MacBook-Pro:Addon-Tests sdonner$ py.test --base-url https://addons-dev.allizom.org --servicesbaseurl https://services.addons-dev.allizom.org --driver Firefox --variables AMO.json --reruns 5 tests/desktop
================================================== test session starts ===================================================
platform darwin -- Python 2.7.11, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir: /Users/sdonner/Addon-Tests, inifile: setup.cfg
plugins: html-1.8.0, rerunfailures-0.5, selenium-1.2.1, variables-1.4, xdist-1.14
collected 167 items 
tests/desktop/test_api_only.py .....
tests/desktop/test_collections.py …
=> Update pytest and pytz

tests/desktop/test_layout.py
#832 fix failing test - test_that_checks_amo_logo_text_layout_and_title
=> #832 fix test_layout

pages/desktop/base.py, pages/desktop/details.py, pages/desktop/user.py, tests/desktop/test_collections.py
removed test_user_my_favorites_page and related calls, since the 'add to collections/favorites' links from add-on/theme pages went away
=> removed test_user_my_favorites_page

pages/desktop/details.py, tests/desktop/test_details_page.py
Rebases and squashes @krupa's changes from #834
=> Remove test_that_add_to_collection_flyout_for_anonymous_users

pages/desktop/details.py, pages/desktop/regions/image_viewer.py, tests/desktop/test_details_page.py, tests/desktop/test_details_page_against_xml.py
Improved readability and maintainability for the test. May also help with the intermittent failure reported in #841, although I was unable to reproduce this failure locally.
=> Rewrite add-on previews and image viewer page regions

pages/desktop/details.py, pages/desktop/regions/addon.py, tests/desktop/test_details_page.py
=> Improve regions and tests for other add-on by the authors

requirements.txt
This ran and passes for me both locally and via an ad-hoc job: https://pastebin.mozilla.org/8869028
=> pytz -> 2016.4

requirements.txt
Ad-hoc on dev: http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/amo.adhoc/111/console
Pastebin: http://pastebin.com/04vUVvWu
Same passing results locally
@mozilla/web-qa-apprentices ?
=> Bump Pytz + PyJWT

tests/desktop/test_api_only.py
@davehunt r?
This fixes https://github.com/mozilla/Addon-Tests/issues/884
=> Fix returned-status string and test name

Jenkinsfile, setup.cfg, tox.ini
Here's the first pipeline for review! I'll add some initial comments, otherwise I'm keen to get feedback/questions from @rpappalax, @m8ttyB, @stephendonner, and @rbillings.
=> Add Jenkinsfile pipeline

Jenkinsfile
@krupa / @davehunt r?
Here's a test run against dev:
Ad-hoc: http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/amo.adhoc/57/console
=> Update to Windows 10
